services:
  db:
    image: postgres:17.5
    container_name: postgres_17_5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./app:/app
      - ./images:/app/images
      - ./images_source:/app/images_source
    working_dir: /app
    command: ["python", "main.py"]

volumes:
  pg_data:
