version: "3.9"

services:
    api:
        build: ./api
        container_name: api-container
        networks:
            - mynetwork
        ports:
            - "5000:5000"

    client:
        build: ./client
        container_name: client-container
        depends_on:
            - api
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
