global:
  scrape_interval: 15s

# подключение алертов
rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


# добавление exporter.py для Linux
  - job_name: 'python_exporter'
    static_configs:
      - targets: ['172.17.0.1:8000']

## добавление exporter.py для на Mac/Window
#  - job_name: 'python_exporter'
#    static_configs:
#      - targets: ['host.docker.internal:8000']  # на Mac/Windows
#